### PR TITLE
issue/15 - Allow language translations to be handled by WP repo

### PR DESCRIPTION
**Pull request by dbeja**
Issue #15 

**Housekeeping**

* [x] Issue number has been linked below the description
* [x] Branch name follows the `issue/###` or `release/###` format
* [x] PR title is prefixed with the branch name (issue/### - Title)

**Proposed changes**

* [x] Code has been tested with no errors
* [x] Code meets stated minimum requirements
* [x] Code should (usually) not contain unrelated changes
* [x] Code style (including docs) and organization is generally consistent with the rest of the codebase
* [x] Before and after screenshots have been posted to document visual changes
* [x] Clear steps for testing the PR have been posted (as needed)

**Implemented changes**
* Increased "Requires at least" to 4.6 on readme header
* Removed loading of text domain
* Removed plugin translations
* Removed domain path from plugin header

### CODE REVIEW

**Comment by DrewAPicture** [comment]
Like I mentioned on https://github.com/AffiliateWP/affiliatewp-affiliate-info/pull/25, we need to leave the language files in place for the first release after we've switched to using .org so it has the opportunity to import the translations we already have.

**Comment by dbeja** [comment]
Languages folder re-added, @DrewAPicture. Is this enough or do I also need to put it back the `Domain Path` on the plugin header?

**Comment by DrewAPicture** [comment]
> Languages folder re-added, @DrewAPicture. Is this enough or do I also need to put it back the `Domain Path` on the plugin header?

The files themselves should be all we need.

**Review by DrewAPicture — APPROVED** [review]
Looks good. Base changed to `release/1.1`

**Pull request merged**
